# .github/workflows/build-macos.yml

name: Build macOS Application

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          
      - name: Install PortAudio
        run: brew install portaudio

      # --- THE FIX: Create placeholder icon file before build ---
      - name: Create Placeholder Icon
        run: |
          mkdir -p assets
          # Create a minimal, blank .icns file. You can replace this later.
          touch assets/logo.icns

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build with PyInstaller
        run: pyinstaller TranscriptionOli.spec

      - name: Zip the .app bundle
        run: ditto -c -k --sequesterRsrc --keepParent dist/TranscriptionOli.app dist/TranscriptionOli_macOS.zip

      - name: Upload Application Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TranscriptionOli-macOS-App
          path: dist/TranscriptionOli_macOS.zip