name: Build macOS Application

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    # --- THE FIX: Switch to the newest Apple Silicon runner ---
    runs-on: macos-14

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          
      # Homebrew is pre-installed on this runner
      - name: Install build dependencies using Homebrew
        run: brew install portaudio
      
      # --- THE NEW STRATEGY: Install and copy a native ARM64 ffmpeg ---
      - name: Install and locate FFmpeg
        run: brew install ffmpeg
      - name: Create bin directory and copy FFmpeg for bundling
        run: |
          mkdir -p bin
          # `which ffmpeg` finds the path to the brew-installed binary
          # and we copy it to our local `bin` folder for PyInstaller
          cp $(which ffmpeg) bin/

      - name: Create Valid Placeholder Icon
        run: |
          mkdir -p assets
          curl -L "https://raw.githubusercontent.com/pyinstaller/pyinstaller/v6.9.0/PyInstaller/bootloader/images/icon-windowed.icns" -o "assets/logo.icns"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build with PyInstaller
        run: pyinstaller TranscriptionOli.spec

      - name: Zip the .app bundle
        run: ditto -c -k --sequesterRsrc --keepParent dist/TranscriptionOli.app dist/TranscriptionOli_macOS.zip

      - name: Upload Application Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TranscriptionOli-macOS-App
          path: dist/TranscriptionOli_macOS.zip