name: Build macOS Application

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    # Build natively on Apple Silicon for best performance
    runs-on: macos-14

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          
      - name: Install build dependencies using Homebrew
        run: brew install portaudio
      
      # --- THE DEFINITIVE FIX: Download a STATIC ffmpeg build ---
      - name: Download and prepare static FFmpeg
        run: |
          mkdir -p bin
          # This URL points to a trusted source of static ffmpeg builds for macOS ARM64
          curl -L "https://www.osxexperts.net/ffmpeg61arm.zip" -o ffmpeg.zip
          # The -j flag junk paths, extracts only the ffmpeg file
          unzip -j ffmpeg.zip 'ffmpeg' -d bin/

      - name: Create Valid Placeholder Icon
        run: |
          mkdir -p assets
          curl -L "https://raw.githubusercontent.com/pyinstaller/pyinstaller/v6.9.0/PyInstaller/bootloader/images/icon-windowed.icns" -o "assets/logo.icns"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build with PyInstaller
        run: pyinstaller TranscriptionOli.spec

      - name: Zip the .app bundle
        run: ditto -c -k --sequesterRsrc --keepParent dist/TranscriptionOli.app dist/TranscriptionOli_macOS.zip

      - name: Upload Application Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TranscriptionOli-macOS-App
          path: dist/TranscriptionOli_macOS.zip