# .github/workflows/build-macos.yml

name: Build macOS Application

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          
      - name: Install PortAudio
        run: brew install portaudio

      - name: Create Valid Placeholder Icon
        run: |
          mkdir -p assets
          curl -L "https://raw.githubusercontent.com/pyinstaller/pyinstaller/v6.9.0/PyInstaller/bootloader/images/icon-windowed.icns" -o "assets/logo.icns"

      # --- CORRECTED: Download and prepare FFmpeg ---
      - name: Download and prepare FFmpeg
        run: |
          mkdir -p bin
          # Using a stable 'latest' release from the yt-dlp/FFmpeg-Builds project, which is reliable.
          # The -L flag is crucial to follow the redirect from the 'latest' tag.
          curl -L "https://github.com/yt-dlp/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-macos-x86_64.zip" -o ffmpeg.zip
          unzip ffmpeg.zip
          # The ffmpeg binary is at the root of this specific zip archive.
          mv ffmpeg bin/ffmpeg

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build with PyInstaller
        run: pyinstaller TranscriptionOli.spec

      - name: Zip the .app bundle
        run: ditto -c -k --sequesterRsrc --keepParent dist/TranscriptionOli.app dist/TranscriptionOli_macOS.zip

      - name: Upload Application Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TranscriptionOli-macOS-App
          path: dist/TranscriptionOli_macOS.zip