# .github/workflows/windows-build.yml

name: Build Windows Executable
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Create Valid Placeholder Icon
        run: |
          New-Item -ItemType Directory -Force -Path "assets"
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/pyinstaller/pyinstaller/v6.9.0/PyInstaller/bootloader/images/icon-windowed.ico" -OutFile "assets\logo.ico"
        shell: powershell
      - name: Download and prepare FFmpeg
        run: |
          New-Item -ItemType Directory -Force -Path "bin"
          Invoke-WebRequest -Uri "https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-full.7z" -OutFile "ffmpeg.7z"
          7z x ffmpeg.7z
          Copy-Item "ffmpeg-*-full_build/bin/ffmpeg.exe" "bin/ffmpeg.exe"
        shell: powershell
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build with PyInstaller
        run: pyinstaller AutoVerse.spec

      # --- [THE DEFINITIVE FIX] ---
      # REMOVED the "staging" and "Compress-Archive" commands completely.

      - name: Upload Executable Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AutoVerse-Windows-App
          # Point DIRECTLY to the build folder. The action will zip its contents.
          path: dist/AutoVerse_App