# .github/workflows/build-windows.yml

name: Build Windows Executable

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      # --- THE FIX: Create placeholder icon file before build ---
      - name: Create Placeholder Icon
        run: |
          mkdir assets
          # Create a minimal, blank .ico file. You can replace this later.
          echo "" > assets/logo.ico
        shell: cmd

      - name: Download and prepare FFmpeg
        run: |
          New-Item -ItemType Directory -Force -Path "bin"
          Invoke-WebRequest -Uri "https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-full.7z" -OutFile "ffmpeg.7z"
          7z x ffmpeg.7z -offmpeg*
          Copy-Item "ffmpeg-*-full_build/bin/ffmpeg.exe" "bin/ffmpeg.exe"
        shell: powershell

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build with PyInstaller
        run: pyinstaller TranscriptionOli.spec

      - name: Zip the output folder
        run: Compress-Archive -Path dist/TranscriptionOli_App -DestinationPath dist/TranscriptionOli_Windows.zip
        shell: powershell
        
      - name: Upload Executable Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TranscriptionOli-Windows-App
          path: dist/TranscriptionOli_Windows.zip