# .github/workflows/build-windows.yml

name: Build Windows Executable

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Create Valid Placeholder Icon
        run: |
          New-Item -ItemType Directory -Force -Path "assets"
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/pyinstaller/pyinstaller/v6.9.0/PyInstaller/bootloader/images/icon-windowed.ico" -OutFile "assets\logo.ico"
        shell: powershell
        
      - name: Download and prepare FFmpeg
        run: |
          New-Item -ItemType Directory -Force -Path "bin"
          Invoke-WebRequest -Uri "https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-full.7z" -OutFile "ffmpeg.7z"
          # --- THE FIX: Corrected the 7z command ---
          7z x ffmpeg.7z
          Copy-Item "ffmpeg-*-full_build/bin/ffmpeg.exe" "bin/ffmpeg.exe"
        shell: powershell

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build with PyInstaller
        run: pyinstaller AutoVerse.spec

      - name: Zip the output folder
        run: Compress-Archive -Path dist/AutoVerse_App -DestinationPath dist/AutoVerse-Windows-App.zip
        shell: powershell
        
      - name: Upload Executable Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AutoVerse-Windows-App
          path: dist/AutoVerse-Windows-App.zip